<?php

namespace ContainerXjWpD2E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Car\CarController' shared autowired service.
     *
     * @return \App\Controller\Car\CarController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Car/CarController.php';
        include_once \dirname(__DIR__, 4).'/src/Modules/Car/CarModuleInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Modules/Car/CarModule.php';
        include_once \dirname(__DIR__, 4).'/src/Modules/Car/Handler/CarHandler.php';

        $container->services['App\\Controller\\Car\\CarController'] = $instance = new \App\Controller\Car\CarController(new \App\Modules\Car\CarModule(new \App\Modules\Car\Handler\CarHandler(($container->privates['App\\Repository\\CarRepository\\CarRepository'] ?? $container->load('getCarRepositoryService')))));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Car\\CarController', $container));

        return $instance;
    }
}
