<?php

namespace ContainerXjWpD2E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreditControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Credit\CreditController' shared autowired service.
     *
     * @return \App\Controller\Credit\CreditController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Credit/CreditController.php';
        include_once \dirname(__DIR__, 4).'/src/Modules/Credit/CreditModuleInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Modules/Credit/CreditModule.php';
        include_once \dirname(__DIR__, 4).'/src/Modules/Credit/Handler/CreditHandler.php';

        $container->services['App\\Controller\\Credit\\CreditController'] = $instance = new \App\Controller\Credit\CreditController(new \App\Modules\Credit\CreditModule(new \App\Modules\Credit\Handler\CreditHandler()));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Credit\\CreditController', $container));

        return $instance;
    }
}
