<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXjWpD2E\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXjWpD2E/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXjWpD2E.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXjWpD2E\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXjWpD2E\App_KernelDevDebugContainer([
    'container.build_hash' => 'XjWpD2E',
    'container.build_id' => '24451fca',
    'container.build_time' => 1723818878,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXjWpD2E');
